# Generated by Django 4.2.1 on 2023-05-29 13:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsncode_pk', models.CharField(max_length=10)),
                ('in_stock', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sell_price', models.IntegerField(default=0)),
                ('stock_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_pk', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=180)),
                ('item_detail', models.TextField(max_length=200)),
                ('item_low_stock_alert', models.IntegerField(default=0)),
                ('item_packaging_type', models.CharField(max_length=50)),
                ('item_company', models.CharField(max_length=50)),
                ('hsncodes', models.ManyToManyField(blank=True, related_name='item', related_query_name='item', to='app.hsncode')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('purchase_bill_pk', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(default=datetime.datetime(2023, 5, 29, 13, 24, 17, 788126, tzinfo=datetime.timezone.utc))),
                ('supplier', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Payment is yet to be done'), ('Paid', 'Payment is done')], default='Pending', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SellBill',
            fields=[
                ('sell_bill_pk', models.AutoField(primary_key=True, serialize=False)),
                ('sell_date', models.DateField(default=datetime.datetime(2023, 5, 29, 13, 24, 17, 788126, tzinfo=datetime.timezone.utc))),
                ('supplier', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Payment is yet to be done'), ('Paid', 'Payment is done')], default='Pending', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hsncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hsncode')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('sell_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sellbill')),
            ],
        ),
        migrations.AddField(
            model_name='sellbill',
            name='items',
            field=models.ManyToManyField(through='app.SellItem', to='app.item'),
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsncode', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('pprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sprice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchasebill')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='items',
            field=models.ManyToManyField(through='app.PurchaseItem', to='app.item'),
        ),
    ]
