# Generated by Django 4.2.1 on 2023-05-13 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HSNCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsncode_pk', models.CharField(max_length=10)),
                ('in_stock', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
                ('sales_price', models.IntegerField(default=0)),
                ('stock_value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_pk', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=180)),
                ('item_low_stock_alert', models.IntegerField(default=0)),
                ('item_packaging_type', models.CharField(choices=[('1 Pc', '1 Piece'), ('1 bx', '1 Box'), ('10 Tabs', '10 Tablets')], max_length=7)),
                ('hsncodes', models.ManyToManyField(blank=True, related_name='item', related_query_name='item', to='app.hsncode')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseBill',
            fields=[
                ('purchase_bill_pk', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_date', models.DateField(default=datetime.datetime(2023, 5, 13, 6, 17, 41, 550593, tzinfo=datetime.timezone.utc))),
                ('supplier', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsncode', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('purchase_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchasebill')),
            ],
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='items',
            field=models.ManyToManyField(through='app.PurchaseItem', to='app.item'),
        ),
    ]
