# Generated by Django 4.2.1 on 2023-05-14 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Payment is yet to be done'), ('Paid', 'Payment is done')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 3, 39, 46, 618910, tzinfo=datetime.timezone.utc)),
        ),
    ]
