# Generated by Django 4.2.1 on 2023-05-14 06:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_purchasebill_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBill',
            fields=[
                ('sell_bill_pk', models.AutoField(primary_key=True, serialize=False)),
                ('sell_date', models.DateField(default=datetime.datetime(2023, 5, 14, 6, 54, 3, 612323, tzinfo=datetime.timezone.utc))),
                ('supplier', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Pending', 'Payment is yet to be done'), ('Paid', 'Payment is done')], default='Pending', max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 14, 6, 54, 3, 612323, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='SellItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hsncode')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('sell_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sellbill')),
            ],
        ),
        migrations.AddField(
            model_name='sellbill',
            name='items',
            field=models.ManyToManyField(through='app.SellItem', to='app.item'),
        ),
    ]
