# Generated by Django 4.2.1 on 2023-05-21 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_sales_price_hsncode_sell_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='price',
            new_name='pprice',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 5, 37, 18, 273029, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellbill',
            name='sell_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 5, 37, 18, 273029, tzinfo=datetime.timezone.utc)),
        ),
    ]
