# Generated by Django 4.2.1 on 2023-05-30 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_purchasebill_purchase_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientModel',
        ),
        migrations.RenameModel(
            old_name='Supplier',
            new_name='SupplierModel',
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 6, 37, 52, 811521, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellbill',
            name='sell_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 6, 37, 52, 812719, tzinfo=datetime.timezone.utc)),
        ),
    ]
