# Generated by Django 4.2.1 on 2023-05-30 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_client_clientmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='client_dl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='client_gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='supplier_dl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='suppliermodel',
            name='supplier_gst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 6, 46, 52, 717699, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellbill',
            name='sell_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 30, 6, 46, 52, 717699, tzinfo=datetime.timezone.utc)),
        ),
    ]
