# Generated by Django 4.2.1 on 2023-05-22 05:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_purchasebill_purchase_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellitem',
            old_name='price',
            new_name='sprice',
        ),
        migrations.AddField(
            model_name='sellbill',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 5, 20, 16, 219373, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellbill',
            name='sell_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 5, 20, 16, 219373, tzinfo=datetime.timezone.utc)),
        ),
    ]
