# Generated by Django 4.2.1 on 2023-05-22 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_price_sellitem_sprice_sellbill_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellitem',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 6, 57, 7, 558252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellbill',
            name='sell_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 6, 57, 7, 558252, tzinfo=datetime.timezone.utc)),
        ),
    ]
